
// login
export const LOGIN_REQUEST= 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// post
export const POST_VIEWER_HIDE_FEATURES = "POST_VIEWER_HIDE_FEATURES";
export const POST_VIEWER_SHOW_FEATURES = "POST_VIEWER_SHOW_FEATURES";

// modal
export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_CLOSE = "MODAL_CLOSE";

// menu
export const MENU_SHOW_DEFAULT = "MENU_SHOW_DEFAULT";
export const MENU_SHOW_ALL = "MENU_SHOW_ALL";

// posts
export const POSTS_FETCH_SUCCESS= 'POSTS_FETCH_SUCCESS'
export const POSTS_FETCH_FAILURE= 'POSTS_FETCH_FAILURE'
export const POSTS_FETCH_REQUEST= 'POSTS_FETCH_REQUEST'

// POST
export const POSTS_CREATE_SUCCESS = 'POSTS_CREATE_SUCCESS'
export const POSTS_CREATE_FAILURE = 'POSTS_CREATE_FAILURE'
export const POSTS_CREATE_REQUEST = 'POSTS_CREATE_REQUEST'

export const POST_FETCH_SUCCESS= 'POST_FETCH_SUCCESS'
export const POST_FETCH_FAILURE= 'POST_FETCH_FAILURE'
export const POST_FETCH_REQUEST= 'POST_FETCH_REQUEST'

export const POST_COMMENT_CREATE_REQUEST = 'POST_COMMENT_CREATE_REQUEST'
export const POST_COMMENT_CREATE_FAILURE = 'POST_COMMENT_CREATE_FAILURE'

// PASSWORD
export const PASSWORD_UPDATE_REQUEST = 'PASSWORD_UPDATE_REQUEST'
export const PASSWORD_UPDATE_FAILURE = 'PASSWORD_UPDATE_FAILURE'
export const PASSWORD_UPDATE_SUCCESS = 'PASSWORD_UPDATE_SUCCESS'

// USER
export const USER_FETCH_SUCCESS= 'USER_FETCH_SUCCESS'
export const USER_FETCH_FAILURE= 'USER_FETCH_FAILURE'
export const USER_FETCH_REQUEST= 'USER_FETCH_REQUEST'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'

// USERS
export const USERS_FETCH_SUCCESS= 'USERS_FETCH_SUCCESS'
export const USERS_FETCH_FAILURE= 'USERS_FETCH_FAILURE'
export const USERS_FETCH_REQUEST= 'USERS_FETCH_REQUEST'
