
// authentication
export const LOGIN_SUCCESS_USER = "LOGIN_SUCCESS_USER";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// post
export const POST_VIEWER_HIDE_FEATURES = "POST_VIEWER_HIDE_FEATURES";
export const POST_VIEWER_SHOW_FEATURES = "POST_VIEWER_SHOW_FEATURES";

// menu
export const MENU_SHOW_DEFAULT = "MENU_SHOW_DEFAULT";
export const MENU_SHOW_ALL = "MENU_SHOW_ALL";

// posts
export const POSTS_CREATE_POST = 'POSTS_CREATE_POST'
export const POSTS_LOADED_SUCCESS= 'POSTS_LOADED_SUCCESS'