
// authentication
export const LOGIN_SUCCESS_USER = "LOGIN_SUCCESS_USER";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// post
export const POST_VIEWER_HIDE_FEATURES = "POST_VIEWER_HIDE_FEATURES";
export const POST_VIEWER_SHOW_FEATURES = "POST_VIEWER_SHOW_FEATURES";

// menu
export const MENU_SHOW_DEFAULT = "MENU_SHOW_DEFAULT";
export const MENU_SHOW_ALL = "MENU_SHOW_ALL";

// posts
export const POSTS_CREATE_SUCCESS = 'POSTS_CREATE_SUCCESS'
export const POSTS_CREATE_FAILURE = 'POSTS_CREATE_FAILURE'
export const POSTS_CREATE_REQUEST = 'POSTS_CREATE_REQUEST'

export const POSTS_FETCH_SUCCESS= 'POSTS_FETCH_SUCCESS'
export const POSTS_FETCH_FAILURE= 'POSTS_FETCH_FAILURE'
export const POSTS_FETCH_REQUEST= 'POSTS_FETCH_REQUEST'

// POST
export const POST_FETCH_SUCCESS= 'POST_FETCH_SUCCESS'
export const POST_FETCH_FAILURE= 'POST_FETCH_FAILURE'
export const POST_FETCH_REQUEST= 'POST_FETCH_REQUEST'

export const POST_COMMENT_CREATE_FAILURE = 'POST_COMMENT_CREATE_FAILURE'
export const POST_COMMENT_CREATE_REQUEST = 'POST_COMMENT_CREATE_REQUEST'
