language: node_js
node_js:
 - "node"

notifications:
  email:
    on_failure: change

cache:
  directories:
    - node_modules

deploy:
  provider: heroku
  app: gunnesgard
  api_key:
    secure: $HEROKU_API_KEY