language: node_js
node_js:
 - "node"

services:
  - mongodb

script:
 - npm run test
 - npm run test:integration

notifications:
  email:
    on_failure: change

deploy:
  on:
    branch: master
  provider: heroku
  app: gunnesgard
  api_key:
    secure: $HEROKU_API_KEY
